package store

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"strings"
	"testing"
	"time"
)

// TestSessionTokenStoredAsDigest pins C8 from the 2026-07-26 hostile review.
//
// Until 2026-07-25 the sessions table's primary key WAS the cookie value: the
// 64 hex chars generated by newSessionToken went to CreateSession and to
// Set-Cookie unchanged. The database file is world-readable and copied verbatim
// to iCloud, so a single read of it was full account takeover for every live
// session (76 of them, 30-day TTL). What is persisted must be a value the
// cookie cannot be recovered from, and presenting THAT value must not
// authenticate — otherwise the digest is just a second password.
func TestSessionTokenStoredAsDigest(t *testing.T) {
	st := openTemp(t)
	ctx := context.Background()

	uid, err := st.CreateUser(ctx, "digestuser", "hash", false)
	if err != nil {
		t.Fatalf("create user: %v", err)
	}
	const cookie = "1f0c8e5a-plaintext-session-token"
	if err := st.CreateSession(ctx, cookie, uid, time.Now().Add(time.Hour).Unix()); err != nil {
		t.Fatalf("create session: %v", err)
	}

	var stored string
	if err := st.db.QueryRowContext(ctx,
		`SELECT token FROM sessions WHERE user_id=?`, uid).Scan(&stored); err != nil {
		t.Fatalf("read stored token: %v", err)
	}
	if stored == cookie || strings.Contains(stored, cookie) {
		t.Fatalf("session token persisted in cleartext: stored=%q", stored)
	}
	sum := sha256.Sum256([]byte(cookie))
	if want := sessionTokenScheme + hex.EncodeToString(sum[:]); stored != want {
		t.Fatalf("stored=%q want the tagged SHA-256 digest %q", stored, want)
	}

	// The cookie still authenticates: the digest is applied on both sides.
	if got, ok, err := st.SessionUser(ctx, cookie); err != nil || !ok || got != uid {
		t.Fatalf("cookie no longer authenticates: %v ok=%v uid=%d", err, ok, got)
	}
	// The stored value must NOT authenticate — a DB reader gains nothing.
	if _, ok, _ := st.SessionUser(ctx, stored); ok {
		t.Fatalf("the stored digest replays as a session cookie")
	}
	// Logout must still find the row from the plaintext it was handed.
	if err := st.DeleteSession(ctx, cookie); err != nil {
		t.Fatalf("delete: %v", err)
	}
	if _, ok, _ := st.SessionUser(ctx, cookie); ok {
		t.Fatalf("deleted session still authenticates")
	}
}

// TestLegacyPlaintextSessionsInvalidated covers the migration that cannot
// happen: the digest of a plaintext we no longer hold is unrecoverable, so
// pre-fix rows can only be invalidated, never converted. They must (a) stop
// authenticating the moment the hashed lookup lands and (b) be deleted, so a
// stale bearer credential does not sit in the DB file forever.
func TestLegacyPlaintextSessionsInvalidated(t *testing.T) {
	st := openTemp(t)
	ctx := context.Background()

	uid, err := st.CreateUser(ctx, "legacyuser", "hash", false)
	if err != nil {
		t.Fatalf("create user: %v", err)
	}
	now := time.Now().Unix()
	// Exactly what the pre-fix CreateSession wrote: the cookie, verbatim.
	const legacy = "legacy-plaintext-cookie-value"
	if _, err := st.w.ExecContext(ctx,
		`INSERT INTO sessions (token, user_id, created_ts, expires_ts) VALUES (?,?,?,?)`,
		legacy, uid, now, now+3600); err != nil {
		t.Fatalf("seed legacy row: %v", err)
	}

	if _, ok, _ := st.SessionUser(ctx, legacy); ok {
		t.Fatalf("legacy plaintext session still authenticates")
	}
	if err := st.PruneSessions(ctx); err != nil {
		t.Fatalf("prune: %v", err)
	}
	var n int
	if err := st.db.QueryRowContext(ctx, `SELECT COUNT(*) FROM sessions`).Scan(&n); err != nil {
		t.Fatalf("count: %v", err)
	}
	if n != 0 {
		t.Fatalf("%d legacy plaintext session row(s) survived the prune", n)
	}

	// A live hashed session must survive the same prune.
	if err := st.CreateSession(ctx, "fresh-token", uid, now+3600); err != nil {
		t.Fatalf("create session: %v", err)
	}
	if err := st.PruneSessions(ctx); err != nil {
		t.Fatalf("prune: %v", err)
	}
	if _, ok, _ := st.SessionUser(ctx, "fresh-token"); !ok {
		t.Fatalf("prune deleted a live hashed session")
	}
}
