#!/usr/bin/env python3
"""Generate controls evidence table from Go source.

Why: Two controls were documented as IN FORCE while unimported (TradableAt
returned empty for its entire life; MarkDelisted had no callers).
"""

import argparse
import os
import re
import sys
import io

CONTROLS = [
    ("Model registry, health grading, retirement", "internal/modelhealth"),
    ("Canary / staged model rollout", "internal/canary"),
    ("Multi-source price validation", "internal/pricecheck"),
    ("Dataset versioning and checksums", "internal/datasetver"),
    ("Corporate actions / split repair", "internal/splitfix"),
    ("Data licensing + HTTP 451 export guard", "internal/datalicense"),
    ("No look-ahead, purge/embargo (cross-sectional)", "internal/alphax"),
    ("No look-ahead, fill timing (backtest)", "internal/backtest"),
    ("Data quality, freshness, dq-auditor", "internal/maintain"),
    ("Pre-trade risk admission", "internal/riskgate"),
    ("Kill switch", "internal/killswitch"),
    ("Portfolio optimiser (NOT bound to allocation)", "internal/portopt"),
]

TEST_FUNC_RE = re.compile(r'^func (Test|Fuzz|Example)\w*')
IMPORT_PATH_TEMPLATE = r'"[^"]*/%s"'

def count_tests(package_dir):
    """Count test functions in *_test.go files directly in package_dir."""
    if not os.path.isdir(package_dir):
        return 0
    count = 0
    for entry in sorted(os.listdir(package_dir)):
        if entry.endswith('_test.go'):
            filepath = os.path.join(package_dir, entry)
            with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
                for line in f:
                    if TEST_FUNC_RE.match(line):
                        count += 1
    return count

def count_wired(daemon_dir, package_import_suffix):
    """Count distinct non-test .go files outside the package that import it."""
    package_path = os.path.normpath(os.path.join(daemon_dir, package_import_suffix))
    pattern = re.compile(IMPORT_PATH_TEMPLATE % re.escape(package_import_suffix))
    wired_files = set()
    for root, dirs, files in os.walk(daemon_dir):
        dirs.sort()  # deterministic walk
        for fname in sorted(files):
            if not fname.endswith('.go'):
                continue
            if fname.endswith('_test.go'):
                continue
            filepath = os.path.normpath(os.path.join(root, fname))
            # Skip if inside the package's own directory
            if filepath.startswith(package_path + os.sep) or filepath == package_path:
                continue
            # Read and search for import
            with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
                content = f.read()
                if re.search(pattern, content):
                    wired_files.add(filepath)
    return len(wired_files)

def render_markdown():
    lines = [
        "<!-- BEGIN GENERATED controls_evidence -->",
        "",
        "Generated by `tools/controls_evidence.py` from the Go source. Do not edit by hand.",
        "**Tests** is the package's own test-function count. **Wired** is the number of non-test files outside the package that import it — a control nothing imports in production is not a control.",
        "",
        "| Control | Package | Tests | Wired |",
        "|---|---|---:|---:|",
    ]
    for label, suffix in CONTROLS:
        # Assume repo root is parent of parent of script's directory
        script_dir = os.path.dirname(os.path.abspath(__file__))
        repo_root = os.path.abspath(os.path.join(script_dir, "..", ".."))
        daemon_dir = os.path.join(repo_root, "daemon")
        package_dir = os.path.join(daemon_dir, suffix)
        tests = count_tests(package_dir)
        wired = count_wired(daemon_dir, suffix)
        lines.append(f"| {label} | `{suffix}` | {tests} | {wired} |")
    lines.extend([
        "",
        "<!-- END GENERATED controls_evidence -->",
    ])
    return "\n".join(lines)

BEGIN = "<!-- BEGIN GENERATED controls_evidence -->"
END = "<!-- END GENERATED controls_evidence -->"


def measure(daemon_dir):
    """[(label, suffix, tests, wired)] in manifest order."""
    return [(label, suffix,
             count_tests(os.path.join(daemon_dir, suffix)),
             count_wired(daemon_dir, suffix))
            for label, suffix in CONTROLS]


def render(rows):
    lines = [
        BEGIN, "",
        "Generated by `tools/controls_evidence.py` from the Go source. Do not edit by hand.",
        "**Tests** is the package's own test-function count. **Wired** is the number of "
        "non-test files outside the package that import it — a control nothing imports in "
        "production is not a control.",
        "",
        "| Control | Package | Tests | Wired |",
        "|---|---|---:|---:|",
    ]
    for label, suffix, tests, wired in rows:
        lines.append("| %s | `%s` | %d | %d |" % (label, suffix, tests, wired))
    lines += ["", END]
    return "\n".join(lines)


def inject(path, block):
    """Splice block between the marker pair in path. Returns False if absent."""
    with io.open(path, encoding="utf-8") as fh:
        text = fh.read()
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0 or j < i:
        print("%s: no %s / %s marker pair" % (path, BEGIN, END), file=sys.stderr)
        return False
    out = text[:i] + block + text[j + len(END):]
    if out != text:
        with io.open(path, "w", encoding="utf-8", newline="") as fh:
            fh.write(out)
    return True


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    parser = argparse.ArgumentParser(description="Generate the controls evidence table.")
    parser.add_argument("--repo", default=os.path.abspath(os.path.join(here, "..")),
                        help="Repo root (default: the tools/ directory's parent)")
    parser.add_argument("--write", default=None, help="write the block to PATH")
    parser.add_argument("--inject", nargs="*", default=[], metavar="DOC",
                        help="splice the block into each DOC's marker pair")
    parser.add_argument("--check", action="store_true",
                        help="exit 1 if any control measures 0 tests or 0 non-test importers")
    args = parser.parse_args()

    rows = measure(os.path.join(os.path.abspath(args.repo), "daemon"))

    if args.check:
        rc = 0
        for label, suffix, tests, wired in rows:
            why = []
            if tests == 0:
                why.append("0 tests")
            if wired == 0:
                why.append("0 non-test importers")
            if why:
                print("%s (%s): %s — a control with no evidence cannot be published "
                      "as IN FORCE" % (label, suffix, ", ".join(why)), file=sys.stderr)
                rc = 1
        sys.exit(rc)

    block = render(rows)
    if args.write:
        with io.open(args.write, "w", encoding="utf-8", newline="") as fh:
            fh.write(block + "\n")
    for doc in [p.strip() for p in args.inject if p.strip()]:
        if not inject(doc, block):
            sys.exit(1)
    if not args.write and not args.inject:
        print(block)


if __name__ == "__main__":
    main()