"""Estimand definitions live in code so they are versioned, testable, and
machine-readable. Prose drifts; this dictionary does not."""

ESTIMANDS = {
    "unconditional_direction_accuracy": {
        "estimand": "Probability that the predicted direction matches the realized direction across all graded rows",
        "universe": "tradable universe",
        "horizon": "1d and 1w",
        "timestamp": "decision-time bar close, never filing or transaction time",
        "outcome": "realized direction",
        "eligible_rows": "all graded rows",
        "dedup_key": "(symbol_id, horizon, settle day)",
        "baseline": "prevailing majority class accuracy",
        "baseline_source": "prequential majority baseline",
        "baseline_uncertainty": "day-clustered Wilson interval, multiplicity-corrected z (a binomial interval would assume independent rows; measured design effect is 13.4x)",
        "paired": True,
    },
    "conditional_accuracy": {
        "estimand": "Probability that the predicted direction matches the realized direction restricted to high confidence predictions",
        "universe": "tradable universe",
        "horizon": "1d and 1w",
        "timestamp": "decision-time bar close, never filing or transaction time",
        "outcome": "realized direction",
        "eligible_rows": "rows where absolute predicted probability minus 0.5 exceeds 0.15",
        "dedup_key": "(symbol_id, horizon, settle day)",
        "baseline": "prevailing majority class accuracy on subset",
        "baseline_source": "prequential majority baseline",
        "baseline_uncertainty": "day-clustered Wilson interval, multiplicity-corrected z (a binomial interval would assume independent rows; measured design effect is 13.4x)",
        "paired": True,
    },
    "ranking_skill": {
        "estimand": "Daily Spearman correlation between predicted probability and realized relative return across the panel",
        "universe": "full panel",
        "horizon": "21 and 42",
        "timestamp": "settle_ts (UTC day of settlement)",
        "outcome": "realized relative return",
        "eligible_rows": "all symbols with predictions and returns",
        "dedup_key": "(symbol_id, horizon, settle day)",
        "baseline": "zero correlation",
        "baseline_source": "out-of-sample zero baseline",
        "baseline_uncertainty": "Fisher transformation confidence interval",
        "paired": False,
    },
    "calibration": {
        "estimand": "Predicted probability versus realized frequency in fixed width bins across the tradable universe",
        "universe": "tradable universe",
        "horizon": "1d",
        "timestamp": "decision-time bar close, never filing or transaction time",
        "outcome": "realized direction frequency",
        "eligible_rows": "all graded rows with predicted probabilities",
        "dedup_key": "(symbol_id, horizon, settle day)",
        "baseline": "identity diagonal",
        "baseline_source": "preregistered identity baseline",
        "baseline_uncertainty": "day-clustered Wilson interval per bin (rows within a day share one outcome driver)",
        "paired": False,
    },
    "cross_sectional_relative_return_skill": {
        "estimand": "Probability that a name beats its day cross sectional median return in the strict universe",
        "universe": "strict universe",
        "horizon": "21 and 42",
        "timestamp": "settle_ts (UTC day of settlement)",
        "outcome": "beats cross sectional median",
        "eligible_rows": "all symbols in strict universe with returns",
        "dedup_key": "(symbol_id, horizon, settle day)",
        "baseline": "0.558 at 21 days and 0.565 at 42 days",
        "baseline_source": "universe construction baseline",
        "baseline_uncertainty": "block bootstrap confidence interval",
        "paired": False,
    },
    "portfolio_performance": {
        "estimand": "Net Sharpe ratio of a long short book after transaction costs across the liquid universe",
        "universe": "liquid universe",
        "horizon": "1d",
        "timestamp": "decision-time bar close (entry priced at next open)",
        "outcome": "net portfolio return",
        "eligible_rows": "all symbols in liquid universe with positions",
        "dedup_key": "(book, settle day) - one book per day, not per symbol",
        "baseline": "zero excess return",
        "baseline_source": "walk-forward zero baseline",
        "baseline_uncertainty": "block bootstrap or Newey-West standard error",
        "paired": False,
    },
}


def get(name):
    return ESTIMANDS[name]