#!/usr/bin/env python3
"""Generate DOCS_INDEX.md from ops/docs-registry.json to prevent hand-maintenance drift."""

import json
import argparse
import pathlib
import sys

REQUIRED_FIELDS = ["owner", "version", "data_as_of", "status", "backtest_data"]
STATUS_ORDER = ["DRAFT", "ACTIVE", "FROZEN", "NOT_AUTHORITATIVE", "SUPERSEDED"]
BACKTEST_ORDER = ["none", "pre-survivorship-fix", "post-survivorship-fix"]

def render(registry: dict) -> str:
    lines = []
    warnings = []
    
    lines.append("# Document index")
    lines.append("")
    lines.append(
        "> This file is generated by `tools/gen_docs_index.py` from "
        "`ops/docs-registry.json`; edit the registry, not this file."
    )
    lines.append("")
    
    # Governed documents section
    lines.append("## Governed documents")
    lines.append("")
    lines.append("| Document | Owner | Version | Data as of | Status | Backtest data |")
    lines.append("| --- | --- | --- | --- | --- | --- |")
    
    strategy_docs = registry.get("strategy_docs", {})
    sorted_docs = sorted(strategy_docs.items())
    
    for filename, meta in sorted_docs:
        row = []
        row.append(f"[{filename}]({filename})")
        
        missing_fields = []
        for field in REQUIRED_FIELDS:
            value = meta.get(field, "")
            if not value:
                missing_fields.append(field)
                row.append("—")
            else:
                # Escape pipe characters in the cell value
                escaped = str(value).replace("|", "\\|")
                row.append(escaped)
        
        if missing_fields:
            warnings.append((filename, missing_fields))
        
        lines.append("| " + " | ".join(row) + " |")
    
    # Not governed section
    lines.append("")
    lines.append("## Not governed")
    lines.append("")
    exempt = sorted(registry.get("exempt", []))
    if exempt:
        lines.append(
            "The following files are excluded from the publication gate by explicit "
            "registration:"
        )
        lines.append("")
        for filename in exempt:
            lines.append(f"- [{filename}]({filename})")
    else:
        lines.append("No exempt documents.")
    
    # Counts section
    lines.append("")
    lines.append("## Counts")
    lines.append("")
    lines.append(
        f"{len(strategy_docs)} governed document(s), {len(exempt)} exempt."
    )
    
    # Warnings section (only if needed)
    if warnings:
        lines.append("")
        lines.append("## Warnings")
        lines.append("")
        for filename, fields in warnings:
            lines.append(
                f"- `{filename}` is missing: {', '.join(fields)}"
            )
    
    return "\n".join(lines) + "\n"

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--repo",
        default=".",
        help="Repository root path (default: current directory)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare generated output against existing DOCS_INDEX.md; exit 1 if different",
    )
    args = parser.parse_args()
    
    repo = pathlib.Path(args.repo).resolve()
    registry_path = repo / "ops" / "docs-registry.json"
    index_path = repo / "DOCS_INDEX.md"
    
    # Read and parse registry
    try:
        with open(registry_path, "r", encoding="utf-8") as f:
            registry = json.load(f)
    except FileNotFoundError:
        print(f"Error: Registry file not found: {registry_path}", file=sys.stderr)
        sys.exit(2)
    except json.JSONDecodeError as e:
        print(f"Error: Malformed JSON in {registry_path}: {e}", file=sys.stderr)
        sys.exit(2)
    
    # Generate content
    content = render(registry)
    content_bytes = content.encode("utf-8")
    
    if args.check:
        # Compare with existing file (if any)
        try:
            with open(index_path, "rb") as f:
                existing = f.read()
            # Normalize to LF for comparison
            existing_normalized = existing.replace(b"\r\n", b"\n")
            content_normalized = content_bytes.replace(b"\r\n", b"\n")
            if existing_normalized == content_normalized:
                sys.exit(0)
            else:
                # Count differing lines
                existing_lines = existing_normalized.split(b"\n")
                content_lines = content_normalized.split(b"\n")
                diff_count = 0
                for i, (a, b) in enumerate(zip(existing_lines, content_lines)):
                    if a != b:
                        diff_count += 1
                # Handle length difference
                diff_count += abs(len(existing_lines) - len(content_lines))
                print(
                    f"DOCS_INDEX.md is stale: {diff_count} line(s) differ",
                    file=sys.stderr,
                )
                sys.exit(1)
        except FileNotFoundError:
            # File doesn't exist, so it's stale
            print("DOCS_INDEX.md is stale: file does not exist", file=sys.stderr)
            sys.exit(1)
    else:
        # Write the file
        with open(index_path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        sys.exit(0)

if __name__ == "__main__":
    main()