#!/usr/bin/env python3
"""The ONLY place the live accuracy record is rendered.

WHY THIS EXISTS. On 2026-08-04 this repository published four mutually
contradictory live directional records at the same time:

    48.1% / 54.6%  over 13,058   PREDICTION_PROCESS.md, CASE_STUDY.md, ...
    48.0% / 54.4%  over 12,696   SHIP_READINESS.md, INSTITUTIONAL_GAP.md, ...
    46.7%          over  8,191   MCP_SERVER.md, LANDING_PAGE_SUPERPROMPT.md, ...
    46.3% / 52.9%  over  2,257   HOW_PREDICTORS_WORK.md

Every one of them was correct on the day it was typed, and not one of them said
so, because each was typed by hand into a different document while the registry
kept re-grading underneath. A reader had no way to tell which was current, and
the honest ones looked like the stale ones.

The fix is that no document types the number at all. This script reads
data/accuracy_registry.json, renders one block, and either writes it to
partials/live_accuracy.md, splices it into documents between marker comments,
or fails a build. Three modes, one source, no hand-typed accuracy anywhere.

    --write            render partials/live_accuracy.md
    --inject DOC...    splice the block into each DOC's marker pair
    --check            fail (1) if the partial or any --inject block has drifted
    --scan DOC...      fail (1) on a SUPERSEDED live-record literal in DOC
    --scan-code SRC... the same gate over source files (.go/.ts/.tsx). Prose was
                       never the only place a number could go stale: the API, the
                       MCP surface and the web UI each carried their own typed
                       copy of this record, disagreeing with each other on the
                       sample size, while the markdown-only gate reported clean.

THE REFUSAL PATH IS LOAD-BEARING. The registry can come back REFUSED with zero
rows — it does that when the grader's hash no longer matches the one pinned on
the pre-registration chain, which is the system working. A generator that
rendered that as an empty table would silently delete the live record from every
document that includes it. Instead the last successful grade is rendered and the
staleness is stated in the block itself.

NO INTERVAL-BASED VERDICT IS PUBLISHED WHILE INTERVALS ARE WITHHELD. The
registry currently reports ci_method="withheld" on every row. A pass/fail read
off a point estimate with no interval is the exact error this platform exists to
refuse, so the Interval column says "withheld" and no verdict is derived from
it. Insufficiency notices the registry itself wrote (n too small, too few
distinct days) are listed below the table — those are statements about the
sample, not verdicts about skill.

Reads two files and writes markdown. It cannot touch the database, cannot alter
a statistic, and cannot repair a document's prose — its only power is to
overwrite a delimited block and to fail a build.

Exit codes: 0 = clean; 1 = drift or a superseded literal; 2 = could not run.

Run: python3 tools/live_accuracy.py --write
     python3 tools/live_accuracy.py --check --inject $(cat partials/INCLUDES.txt)
"""
import argparse
import io
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_REGISTRY = os.path.join(REPO, "data", "accuracy_registry.json")
DEFAULT_OUT = os.path.join(REPO, "partials", "live_accuracy.md")

BEGIN = "<!-- BEGIN GENERATED live_accuracy -->"
END = "<!-- END GENERATED live_accuracy -->"

# README.md carries a SECOND generated live-record block, rendered by
# ops/accuracy-registry.sh from the SAME data/accuracy_registry.json. One
# canonical source, two renderers. The scan must recognise its markers or it
# reports a legitimately generated table as hand-typed -- which it did, naming
# every figure in the README's own auto-generated block.
#
# KNOWN RULE 3 SMELL, recorded rather than hidden: two renderers of one record
# is one renderer too many. The original note here said they "cannot currently
# disagree, because both read the same JSON and both are regenerated by
# committed tooling". That was WRONG, and 2026-07-27:A8 is the finding: they
# read the same JSON but are regenerated at DIFFERENT TIMES. The README block is
# rewritten only by ops/accuracy-registry.sh, while the JSON can be regenerated
# on its own -- so the README goes on publishing a superseded grade, and nothing
# noticed. Measured 2026-08-12: the README block said directional-ensemble (1w)
# FAILED at 36.5% while the registry said INSUFFICIENT DAYS at 38.8%; a
# DIFFERENT VERDICT, not a rounding drift. check_readme_freshness below closes
# it, using the timestamp the block already stamps on itself. The consolidation
# -- README including partials/live_accuracy.md like every other document in
# partials/INCLUDES.txt -- is deliberately NOT done here: it would rewrite the
# repository's front page during a re-grade, and this scan does not need it to
# be correct. See proofs/P9_REGRADE_VERIFICATION.md.
README_BEGIN = "<!-- LIVE-ACCURACY:BEGIN -->"
README_END = "<!-- LIVE-ACCURACY:END -->"

# Live-record numbers this repository published before 2026-08-04 and no longer
# stands behind. They are not wrong — they were the record on their own date —
# but a document that states one as CURRENT is republishing a superseded grade.
# Percentages and sample sizes both, because "46.7% over 8,191" identifies the
# snapshot twice and either half alone is enough to date it.
SUPERSEDED_LITERALS = [
    "48.1%", "54.6%", "48.0%", "54.4%", "46.7%", "46.2%", "48.6%", "56.2%",
    "46.3%", "52.9%",
    "13,058", "13,044", "12,696", "8,191", "18,762", "9,164", "8,272", "2,257",
]

# A document carrying this marker is declaring itself a dated record rather than
# a live claim, so its numbers are history and the scan leaves it alone.
HISTORICAL_MARKER = "SUPERSEDED-SNAPSHOT"


def die(msg):
    print(msg, file=sys.stderr)
    sys.exit(2)


def load_snapshot(path):
    """Return (snapshot, banner) — the authoritative grade and its staleness.

    banner is None when the top-level registry is itself publishable.
    """
    try:
        with open(path, encoding="utf-8") as f:
            reg = json.load(f)
    except FileNotFoundError:
        die("registry not found: %s" % path)
    except (OSError, ValueError) as e:
        die("registry unreadable: %s: %s" % (path, e))

    rows = reg.get("rows") or []
    if rows and reg.get("status") != "REFUSED":
        return reg, None

    stale = reg.get("stale_last_registry") or {}
    if not (stale.get("rows") or []):
        die("registry has no publishable rows and no last successful grade "
            "under stale_last_registry — refusing to render an empty table")
    banner = {
        "status": reg.get("status", "REFUSED"),
        "reason": reg.get("refusal_reason", "unstated"),
        "age": reg.get("last_successful_grade_age", "unknown"),
        "graded_at": stale.get("graded_at") or stale.get("generated") or "unknown",
    }
    return stale, banner


def pct(x):
    return "—" if x is None else "%.1f%%" % (100.0 * x)


def pp(x):
    return "—" if x is None else "%+.1fpp" % (100.0 * x)


def cell(s):
    return str(s).replace("|", "\\|")


def interval(row):
    ci = row.get("ci")
    if isinstance(ci, (list, tuple)) and len(ci) == 2 and None not in ci:
        return "[%s, %s]" % (pct(ci[0]), pct(ci[1]))
    return cell(row.get("ci_method") or "withheld")


def is_live(row):
    n = row.get("live_n")
    return isinstance(n, int) and n > 0


def render(snapshot, banner, registry_path):
    rel = os.path.relpath(registry_path, REPO).replace("\\", "/")
    graded = snapshot.get("graded_at") or snapshot.get("generated") or "unknown"
    out = [BEGIN, ""]
    out.append("Generated from `%s` (grade of %s) by `tools/live_accuracy.py`. "
               "Do not edit by hand — edit the registry or the generator." % (rel, graded))
    out.append("")

    if banner:
        out.append("> **STALE — this is not a current grade.** The registry is `%s` "
                   "(%s), and the last successful grade is %s old. The numbers below "
                   "are that last successful grade, taken at %s. Nothing here has been "
                   "re-graded since."
                   % (banner["status"], banner["reason"], banner["age"], banner["graded_at"]))
        out.append("")

    live = [r for r in snapshot.get("rows", []) if is_live(r)]
    out.append("### Live record")
    out.append("")
    out.append("| Predictor | Band | n | Live acc | Null | Skill | Distinct days | Interval |")
    out.append("|---|---|---|---|---|---|---|---|")
    for r in live:
        null = r.get("null_prequential")
        if null is None:
            null = r.get("null_acc")
        out.append("| %s | %s | %s | %s | %s | %s | %s | %s |" % (
            cell(r.get("predictor", "?")),
            cell(r.get("band", "all")),
            "{:,}".format(r.get("live_n", 0)),
            pct(r.get("live_acc")),
            pct(null),
            pp(r.get("skill")),
            r.get("distinct_days", 0),
            interval(r),
        ))
    out.append("")

    if live and all(r.get("ci") is None for r in live):
        out.append("Intervals are withheld this cycle, so **no pass/fail verdict is "
                   "published from them**. A point estimate without an interval is not "
                   "a result; treat every row above as a running tally.")
        out.append("")

    byname = {r.get("predictor"): r for r in live}
    notices = [(r.get("predictor", "?"), r["verdict"]) for r in live if r.get("verdict")]
    if notices:
        out.append("Sample-size notices carried by the registry itself (statements about "
                   "the sample, not verdicts about skill):")
        out.append("")
        for name, v in notices:
            out.append("- `%s` — %s" % (name, v))
            # A verdict like "significantly worse than the naive baseline" compares
            # accuracy to a null estimated on the SAME short window, treating the null
            # as exact. tools/selection_honesty.py re-tests the paired difference
            # blocking by day; when that interval contains zero the verdict is not
            # supported and we say so next to it. Disclosure only -- the registry's
            # own verdict string above is left exactly as the pinned grader wrote it.
            res = (byname.get(name, {}).get("honesty") or {}).get("resolvability")
            if res and not res.get("resolvable") and res.get("reason"):
                out.append("  - **not supported by the day count** — %s" % res["reason"])
        out.append("")

    backtested = [r for r in snapshot.get("rows", []) if not is_live(r)]
    if backtested:
        out.append("### Backtested claims with no live record yet")
        out.append("")
        for r in backtested:
            out.append("- `%s` — registered claim %s, %s forecasts recorded, 0 graded. "
                       "Not a live result." % (
                           cell(r.get("predictor", "?")),
                           pct(r.get("claimed")),
                           "{:,}".format(r.get("forecasts_recorded", 0))))
        out.append("")

    mult = []
    for key in ("family_size", "looks", "divisor", "corrected_alpha"):
        if snapshot.get(key) is not None:
            mult.append("%s=%s" % (key, snapshot[key]))
    if mult:
        out.append("**Multiplicity:** " + ", ".join(mult) + ".")
        out.append("")

    surv = ["epoch %s" % snapshot["survivorship_epoch"]] if snapshot.get("survivorship_epoch") else []
    reason = next((r.get("survivorship_reason") for r in snapshot.get("rows", [])
                   if r.get("survivorship_clean") is False and r.get("survivorship_reason")), None)
    if reason:
        surv.append(reason)
    effect = survivorship_effect()
    if effect is not None:
        # The DIRECTION of this bias was already stated in prose ("the published
        # claim is inflated by excluding dead names") while its SIZE sat in a
        # JSON file nobody opens. A known-direction adverse bias that travels
        # without its magnitude is not disclosed, it is merely admitted, so the
        # number is rendered here from the revalidation snapshot.
        surv.append(
            "measured effect %+.2fpp (active-only %.2f%% minus survivorship-clean "
            "%.2f%%, n=%s clean vs %s active, revalidation of %s) — POSITIVE means "
            "the active-only figure is INFLATED by excluding dead names"
            % (100.0 * (effect["active"] - effect["clean"]),
               100.0 * effect["active"], 100.0 * effect["clean"],
               "{:,}".format(effect["n_clean"]), "{:,}".format(effect["n_active"]),
               effect["generated"]))
    if surv:
        out.append("**Survivorship:** " + "; ".join(surv) + ".")
        out.append("")

    out.append(END)
    return "\n".join(out) + "\n"


REVALIDATION_STATUS = os.path.join(REPO, "ops", "revalidation-status.json")


def survivorship_effect(path=REVALIDATION_STATUS):
    """Active-only accuracy minus survivorship-clean accuracy, from the snapshot.

    Returns None when the monthly revalidation has not run, or has not written
    both arms — an absent measurement must read as absent rather than as zero
    effect, which is the direction that would flatter the record.
    """
    try:
        with io.open(path, encoding="utf-8") as fh:
            snap = json.load(fh)
    except (OSError, ValueError):
        return None
    arms = snap.get("arms") or {}
    active, clean = arms.get("active_only"), arms.get("survivorship_clean")
    if not active or not clean:
        return None
    if active.get("accuracy") is None or clean.get("accuracy") is None:
        return None
    return {
        "active": active["accuracy"], "clean": clean["accuracy"],
        "n_active": active.get("n", 0), "n_clean": clean.get("n", 0),
        "generated": snap.get("generated", "unknown"),
    }


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def write(path, text):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)


def find_block(text, path):
    """Return (start, end) span of the marker pair, or exit 1 if absent."""
    b = text.find(BEGIN)
    e = text.find(END, b) if b != -1 else -1
    if b == -1 or e == -1:
        print("%s: no %s ... %s marker pair to fill" % (path, BEGIN, END))
        return None
    return b, e + len(END)


def inject(path, block):
    text = read(path)
    span = find_block(text, path)
    if span is None:
        return False
    # The block is rstripped: the standalone partial file ends with a newline,
    # but the document already owns whatever follows its END marker. Splicing
    # both in would add a blank line on every run — a diff that never converges.
    write(path, text[:span[0]] + block.rstrip("\n") + text[span[1]:])
    return True


def block_matches(path, block):
    text = read(path)
    span = find_block(text, path)
    if span is None:
        return False
    return text[span[0]:span[1]] == block.rstrip("\n")


def current_literals(snapshot):
    """The live figures of the CURRENT grade.

    Banned outside a generated block for the same reason the superseded ones
    are: a correct number typed by hand today is a superseded number typed by
    hand tomorrow. FC1 was not caused by wrong figures — every one of the four
    was right when it was typed.
    """
    lits = set()
    for r in snapshot.get("rows", []):
        n = r.get("live_n")
        # Rows below the registry's own minimum are not a published record, and
        # their figures are not distinctive enough to identify one.
        if not is_live(r) or n < 30:
            continue
        for v in (r.get("live_acc"), r.get("null_prequential"), r.get("null_acc")):
            if v is not None:
                lits.add(pct(v))
        if n >= 1000:
            lits.add("{:,}".format(n))
    # 50.0% is the coin flip. It appears legitimately in every document that
    # discusses a baseline at all, so banning it would train people to ignore
    # this check — the one failure mode a lint cannot survive.
    lits.discard("50.0%")
    return sorted(lits)


def scan(path, extra_literals=(), allow_whole_file_escape=True):
    """Report banned live-record literals. Returns a list of (line, literal).

    allow_whole_file_escape=False refuses the file-level HISTORICAL_MARKER and
    honours only block-scoped ones. SOURCE FILES PASS FALSE, and that is the
    point: a document can legitimately be history end to end, but a .go file
    that ships in the running binary never is. Leaving the banner escape
    available to code let one comment in a package header silence the whole
    file — verified by injecting `// SUPERSEDED-SNAPSHOT` above a banned
    literal and watching the violation disappear.

    This gate exists to catch the codebase deceiving itself about its own
    accuracy. A gate the audited thing can switch off is not a gate; the same
    lesson already produced UNSUPPRESSIBLE_CHECKS in tools/docs_gate.py, and
    this is that rule reaching the source scan.
    """
    text = read(path)
    lines = text.splitlines()
    # A whole DOCUMENT can declare itself history, and every such document in
    # this repository does it on line 2. Restricting the whole-file escape to
    # the header keeps a marker buried at line 900 from silently exempting the
    # 899 live claims above it — the escape has to be a banner, not a footnote.
    if allow_whole_file_escape and HISTORICAL_MARKER in "\n".join(lines[:40]):
        return []
    parts = os.path.abspath(path).replace("\\", "/").split("/")
    # audits/ and proofs/ are the same category: dated evidence about a moment,
    # not a live claim. A proof artifact that says "this figure was 48.1% over
    # 13,058 pre-epoch symbol-days, and here is why that is not the current
    # record" is doing the exact job this scan exists to enforce, and banning
    # the literal would make the correction unwritable. The distinction the gate
    # protects is between a document that ASSERTS a live number and one that
    # RECORDS a superseded one; both directories are unambiguously the latter.
    if "audits" in parts or "proofs" in parts:
        return []
    banned = list(SUPERSEDED_LITERALS) + list(extra_literals)
    hits = []
    inside = False
    for n, line in enumerate(lines, 1):
        if BEGIN in line or README_BEGIN in line:
            inside = True
            continue
        if END in line or README_END in line:
            inside = False
            continue
        if inside:
            continue
        for lit in banned:
            if lit in line and not _historical_block(lines, n):
                hits.append((n, lit))
    return hits


# Source files cannot carry a whole-file history banner — a package is not a
# dated record. What they can carry is ONE labelled historical block, which is a
# legitimate thing to render (the accuracy page's pre-epoch retirement panel is
# exactly that). So the marker works at block scope here: it exempts the lines
# beneath it, and only those, so the rest of the file stays under the gate.
HISTORICAL_BLOCK_LINES = 25


def _historical_block(lines, n):
    """True if a HISTORICAL_MARKER labels the block containing line n."""
    start = max(0, n - HISTORICAL_BLOCK_LINES - 1)
    return any(HISTORICAL_MARKER in ln for ln in lines[start:n])


def check_readme_freshness(registry_path, readme_path=None):
    """Does README's generated block render the CURRENT registry?

    2026-07-27:A8 -- "README's auto-updated accuracy block disagrees with the
    registry it claims to render ... nothing detects the disagreement".

    The block stamps the rendering it came from ("_Regenerated <ts>") and the
    registry carries `generated`. Comparing those two is exact: no parsing of
    percentages, no tolerance to argue about, and it catches a verdict change
    just as surely as a rounding change. Returns a list of problems.
    """
    # Resolve the README RELATIVE TO THE REGISTRY, never to the process cwd.
    # A default of "README.md" is the same defect 2026-07-26:A9 was filed for --
    # a relative path that happens to resolve somewhere plausible. It made the
    # test fixtures compare the REAL repo README against a temp-dir registry and
    # fail two unrelated tests. The registry lives at <repo>/data/<file>, so the
    # README is two levels up from it; a fixture registry then looks for a README
    # beside itself, finds none, and the check correctly says nothing.
    if readme_path is None:
        readme_path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(registry_path))), "README.md")
    problems = []
    try:
        with open(registry_path, encoding="utf-8") as f:
            reg_gen = (json.load(f) or {}).get("generated")
    except (OSError, ValueError) as e:
        return [f"{readme_path}: cannot read {registry_path} to compare against ({e})"]
    if not reg_gen:
        return [f"{registry_path}: no `generated` field to compare the README against"]
    if not os.path.exists(readme_path):
        # No README beside this registry (a test fixture, a snapshot dir) means
        # there is no second rendering to disagree with. That is nothing to
        # check, NOT a problem -- reporting it as one made --check fail on
        # fixtures that have no README at all.
        return []
    try:
        text = open(readme_path, encoding="utf-8").read()
    except OSError as e:
        return [f"cannot read {readme_path}: {e}"]
    if README_BEGIN not in text or README_END not in text:
        return []          # no generated block here; nothing to be stale
    block = text.split(README_BEGIN, 1)[1].split(README_END, 1)[0]
    m = re.search(r"_Regenerated\s+(\S+)", block)
    if not m:
        problems.append(
            f"{readme_path}: generated block carries no `_Regenerated <ts>` stamp, so "
            "whether it renders the current registry cannot be checked at all")
        return problems
    stamped = m.group(1).rstrip("· ").strip()
    if stamped != reg_gen:
        problems.append(
            f"{readme_path}: the generated accuracy block renders registry {stamped} "
            f"but data/accuracy_registry.json is {reg_gen} — the README is publishing a "
            "SUPERSEDED grade. Re-render it with ops/accuracy-registry.sh; never hand-edit "
            "the block.")
    return problems


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--registry", default=DEFAULT_REGISTRY)
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--write", action="store_true", help="render --out")
    ap.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    ap.add_argument("--inject", nargs="*", default=[], metavar="DOC")
    ap.add_argument("--scan", nargs="*", default=[], metavar="DOC")
    ap.add_argument("--scan-code", nargs="*", default=[], metavar="SRC",
                    help="the same gate over source files (.go/.ts/.tsx)")
    # --check compares documents against the REGISTRY, so it needs data/, which
    # is gitignored: on a clean CI checkout that step cannot run at all.
    # --check-includes compares documents against the committed PARTIAL instead.
    # Both inputs are git-tracked, so this is the half of the FC1 guard that
    # runs everywhere — and the half that matters most, because it is what stops
    # a document's copy of the table drifting from the one source.
    ap.add_argument("--check-includes", nargs="*", default=None, metavar="DOC",
                    help="verify each DOC's generated block matches --out; needs no registry")
    args = ap.parse_args()

    # partials/INCLUDES.txt is a shared manifest written by more than one tool on
    # a Windows box, so `--inject $(cat partials/INCLUDES.txt)` hands us paths
    # with a trailing CR. Stripping here rather than demanding one line-ending
    # discipline across every writer: the alternative failed with
    # `OSError: Invalid argument: 'CASE_STUDY.md\r'`, which names the file
    # correctly and explains nothing.
    args.inject = [p.strip() for p in args.inject if p.strip()]
    args.scan = [p.strip() for p in args.scan if p.strip()]
    args.scan_code = [p.strip() for p in args.scan_code if p.strip()]
    if args.check_includes is not None:
        args.check_includes = [p.strip() for p in args.check_includes if p.strip()]

    rc = 0
    block = None
    current = []
    if args.check:
        # A8: the README's block and the registry are two renderings of one
        # record, refreshed by different commands. Nothing compared them.
        for problem in check_readme_freshness(args.registry):
            print(problem, file=sys.stderr)
            rc = 1
    if args.write or args.check or args.inject:
        snapshot, banner = load_snapshot(args.registry)
        block = render(snapshot, banner, args.registry)
        current = current_literals(snapshot)
    elif (args.scan or args.scan_code) and os.path.exists(args.registry):
        # --scan alone does not need a rendered block, but the current grade's
        # own figures make it much stronger. When there is no registry (a clean
        # CI checkout — data/ is gitignored) it degrades to the superseded list
        # rather than refusing to run: half a scan that runs everywhere beats a
        # whole one that runs nowhere.
        snapshot, _ = load_snapshot(args.registry)
        current = current_literals(snapshot)

    if args.write and not args.check:
        write(args.out, block)

    if args.check:
        if not os.path.exists(args.out):
            print("%s does not exist — run --write" % args.out, file=sys.stderr)
            rc = 1
        elif read(args.out) != block:
            print("DRIFT: %s no longer matches the registry — run --write" % args.out,
                  file=sys.stderr)
            rc = 1
        for doc in args.inject:
            if not block_matches(doc, block):
                print("DRIFT: %s's generated block no longer matches the registry "
                      "— run --inject" % doc, file=sys.stderr)
                rc = 1
    else:
        for doc in args.inject:
            if not inject(doc, block):
                rc = 1

    if args.check_includes is not None:
        if not os.path.exists(args.out):
            print("%s does not exist — nothing to check documents against" % args.out,
                  file=sys.stderr)
            rc = 1
        else:
            partial = read(args.out)
            for doc in args.check_includes:
                if not block_matches(doc, partial):
                    print("DRIFT: %s's generated block does not match %s — run --inject"
                          % (doc, args.out), file=sys.stderr)
                    rc = 1

    for doc in args.scan:
        for n, lit in scan(doc, current):
            kind = "superseded" if lit in SUPERSEDED_LITERALS else "hand-typed current"
            print("%s:%d: %s live-record literal '%s' — include "
                  "partials/live_accuracy.md instead" % (doc, n, kind, lit))
            rc = 1

    # Source files cannot include the partial, so the remedy differs: read the
    # registry at runtime, or label the block historical and let it be history.
    for src in args.scan_code:
        # allow_whole_file_escape=False: a source file may label a BLOCK
        # historical, never itself. See scan().
        for n, lit in scan(src, current, allow_whole_file_escape=False):
            kind = "superseded" if lit in SUPERSEDED_LITERALS else "hand-typed current"
            print("%s:%d: code %s live-record literal '%s' — read it from "
                  "data/accuracy_registry.json at runtime, or mark the block "
                  "%s" % (src, n, kind, lit, HISTORICAL_MARKER))
            rc = 1

    sys.exit(rc)


if __name__ == "__main__":
    main()
