"""Render SignalDeck's public track-record README from accuracy_registry.json.

jq is absent under Git Bash on Windows, which silently killed
ops/anchor-publish.sh's publish step from 2026-07-27 onward. The repo already
reads JSON and SQLite through Python everywhere for exactly that reason, so
this script replaces the jq program that produced the track-record README.
"""

import json
import sys

sys.stdout.reconfigure(encoding="utf-8")


def pct(x):
    if x is None:
        return "—"
    return f"{round(x * 1000) / 10}%"


def fmt_ci(row):
    ci = row.get("ci")
    if ci is not None:
        lo = round(ci[0] * 1000) / 1000
        hi = round(ci[1] * 1000) / 1000
        return f"[{lo}, {hi}]"
    return row.get("ci_method") or "—"


def esc(x):
    if x is None:
        return ""
    return str(x).replace("|", "\\|")


def main():
    if len(sys.argv) != 2:
        sys.stderr.write("usage: python tools/render_track_record.py <path-to-accuracy_registry.json>\n")
        sys.exit(2)

    path = sys.argv[1]

    try:
        with open(path, encoding="utf-8") as f:
            data = json.load(f)
    except (OSError, json.JSONDecodeError) as e:
        sys.stderr.write(f"error: {e}\n")
        sys.exit(1)

    rows = data.get("rows")
    if not rows:
        sys.stderr.write("error: rows list is missing or empty\n")
        sys.exit(1)

    out = []
    out.append("# SignalDeck — Public Track Record")
    out.append("")
    out.append("Every predictor SignalDeck tracks, rendered verbatim from [`accuracy_registry.json`](accuracy_registry.json) on every publish — FAILED and INSUFFICIENT verdicts included, nothing filtered. A deliberately unflattering public record is the point: it cannot be fabricated overnight, and the commit history of this repo makes later retouching of the past record evident.")
    out.append("")
    out.append(f"- Generated: {data.get('generated', '')}")
    out.append(f"- Minimum independent n for a verdict: {data.get('min_independent_n', '')}")
    out.append(f"- Survivorship epoch: {data.get('survivorship_epoch', '')}")
    out.append(f"- Null policy: {data.get('null_policy', '')}")
    out.append("")
    out.append("| Predictor | Family | Band | n | Accuracy | 95% CI | Prequential null | Verdict | Note |")
    out.append("|---|---|---|--:|--:|---|--:|---|---|")

    for row in rows:
        # `or`, not a .get default. A .get default is returned only when the KEY
        # is ABSENT, so `row.get("live_n", 0)` on {"live_n": null} hands back
        # None and the public table prints the literal string "None" in the n
        # column. The registry writes JSON nulls for withheld values on purpose,
        # so every optional field here is reachable as null.
        predictor = esc(row.get("predictor"))
        family = esc(row.get("family") or "—")
        band = esc(row.get("band"))
        live_n = row.get("live_n") or 0
        live_acc = pct(row.get("live_acc"))
        ci = fmt_ci(row)
        null_prequential = pct(row.get("null_prequential"))
        verdict = esc(row.get("verdict"))
        note = esc(row.get("note") or "")
        out.append(f"| {predictor} | {family} | {band} | {live_n} | {live_acc} | {ci} | {null_prequential} | {verdict} | {note} |")

    out.append("")
    out.append("## Verifying this record")
    out.append("")
    out.append("- `accuracy_registry.json` — the canonical machine-readable registry; this README is a rendering of it, regenerated by `ops/anchor-publish.sh` on every push and never hand-edited.")
    out.append("- `anchors.log` — signed ledger anchor digests, append-only; a digest in the git history of this repo is evidence the operator cannot fabricate after the fact.")
    out.append("- `prereg.log` — pre-registration chain heads: structural claims frozen and timestamped before their outcomes existed.")
    out.append("- `PREREGISTRATION.md` — the frozen 2026-08-14 structural grading protocol (claim freeze, null choice, min-n/min-days gates, no post-hoc slicing); its `shasum -a 256` must equal the specHash of the chain's prereg-document record.")

    sys.stdout.write("\n".join(out) + "\n")
    sys.exit(0)


if __name__ == "__main__":
    main()